# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit murrell-xdvir.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(kableExtra)


## ----echo=FALSE---------------------------------------------------------------
## Parameter for plotting
## Set x variable for the fitness function 
x = seq(-1, 7.5, by = .01)

## Math parameters for Fitness function 
s = .5
m = 1.5
t = 1.7
u = 3.4
div1 = 2.4
div2 = 3.5

## Set population parameters
## NB individuals, try with 10, and 1000 
n = 1000 
## Get fake phenotypes
## Phenotypes for the population
pheno = rnorm(n = n, mean = 3.2, sd = 0.5) 
## Make y height just for vizualisation purpose 
fit = rnorm(length(pheno), mean = .12, sd =.01)


## Load functions ----------------------------------------------------------
## Mathematical fitness function (2 peaks )
## This is a speculative fitness function, you could design your own.
fit.function  <- function(x, s, m, t, u, div1 = 2, div2 = 2.5) {
    exp(-s^(-2)*(x-m)^(2))/div1+exp(-t^(-2)*(x-u)^(2))/div2
}

main.plot <- function(mar = c(3, 3, .25, .25), col = 2) {
    ## Set parameter of plotting area 
    par(mar = mar)
    ## Plot fitness function 
    y = fit.function(x = x,s = s, m = m,t = t,u = u, div1 = div1, div2 = div2)
    plot(y ~ x, 
         xlim = c(-0.5, 7),
         ylim = c(0, .7),
         axes=FALSE,
         type = "l", lwd = 5, col = col, 
         ylab = "Fitness", xlab = "Phenotypes")
    axis(1)
    axis(2, at=seq(0, .6, .2))
    box()
}

## Make a fake population 
add.fake.pop =  function(x = pheno, y = fit,  alp = 1) {
    ## Line at the mean 
    ## abline(v = mean(x), lty = 3)
    ## Calculate the density of the population 
    dens.xy = density(x = x, n = 512, adjust = 2) # Adjust to make it smoother 
    ## Add density 
    lines(x = dens.xy$x, y = dens.xy$y/3, lty = 2)
}


## ----echo=FALSE---------------------------------------------------------------
texStr <- r"(\definecolor{Rred}{RGB}{223,83,107}
\fontsize{12}{15}
\selectfont
\begin{minipage}{3.5in}
We `move' the original population's mean to a new $\bar z_i$ 
and calculate the average fitness at that new mean phenotype 
of the population to get the adaptive landscape, $\bar W_i$, 
then we combine the population mean and the average fitness 
to get the \textcolor{Rred}{fitness function}.
\end{minipage})"


## ----echo=FALSE, dev="png", dev.args=list(type="cairo"), fig.width=7, fig.height=4.5, dpi=300, fig.keep="last"----
par(family="TeX Gyre Adventor", mgp=c(2, .7, 0))
main.plot();
add.fake.pop(alp = .1); 

library(gridGraphics)
grid.echo()
downViewport("graphics-window-1-1")

library(xdvir)
adventor <- fontspecPackage(font="TeX Gyre Adventor", name="adventor")
registerPackage(adventor)

tex <- author(texStr, packages=list(adventor, "xcolor"))
dviFile <- typeset(tex)
dvi <- readDVI(dviFile)
grid.dvi(dvi,
         x=unit(1, "npc") - unit(5, "mm"), y=unit(1, "npc") - unit(5, "mm"),
         hjust="right", vjust="top")

